spring:
  application.name: challenge

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      check-validation:
        check-validation
      check-result:
        check-result
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: check:com.sda.challenge.domain.model.kafka.CheckResultEvent
    consumer:
      group-id: group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: check:com.sda.challenge.domain.model.kafka.CheckEvent